name: carbonvoice_audio
description: A new flutter plugin project.
version: 1.1.7
homepage: "https://github.com/PhononX/carbonvoice_audio"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ffmpeg_kit_flutter: ^4.5.1
  flutter_tts: ^3.3.3 # for text to speech
  speech_to_text: ^5.4.2 # for transcriptions
  just_audio: ^0.9.20 #updated for adding earcons
  audio_service: ^0.18.0
  audio_session: ^0.1.6
  flutter_sound: ^9.1.7
  permission_handler: ^9.1.0
  wakelock: ^0.5.6
  meta: ^1.7.0
  cv_platform_interface:
    git:
      url: https://github.com/PhononX/carbon-voice-audio.git
      ref: 1.0.3
      path: cv_platform_interface
  universal_html: ^2.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.phononx.carbonvoice_audio
        pluginClass: CarbonvoiceAudioPlugin
      ios:
        pluginClass: CarbonvoiceAudioPlugin
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
